global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: 'alerts@adxcore.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        alertname: ServiceDown
      receiver: 'service-down-alerts'
      group_wait: 0s
      repeat_interval: 2m
    - match:
        alertname: SuspiciousActivity
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 1m

receivers:
  - name: 'default'
    email_configs:
      - to: 'ops-team@adxcore.com'
        subject: 'ADX Core Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'ops-team@adxcore.com,management@adxcore.com'
        subject: 'CRITICAL: ADX Core Alert - {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately.
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'CRITICAL: ADX Core Alert'
        text: |
          {{ range .Alerts }}
          🚨 *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.job }}
          {{ end }}
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops-team@adxcore.com'
        subject: 'WARNING: ADX Core Alert - {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: 'WARNING: ADX Core Alert'
        text: |
          {{ range .Alerts }}
          ⚠️ *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.job }}
          {{ end }}

  - name: 'service-down-alerts'
    email_configs:
      - to: 'ops-team@adxcore.com,on-call@adxcore.com'
        subject: 'SERVICE DOWN: {{ .GroupLabels.job }}'
        body: |
          🔴 SERVICE DOWN 🔴
          
          {{ range .Alerts }}
          Service: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Down since: {{ .StartsAt }}
          {{ end }}
          
          Immediate action required!
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'SERVICE DOWN'
        text: |
          {{ range .Alerts }}
          🔴 *Service {{ .Labels.job }} is DOWN*
          Instance: {{ .Labels.instance }}
          {{ end }}
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: 'Service {{ .GroupLabels.job }} is down'

  - name: 'security-alerts'
    email_configs:
      - to: 'security-team@adxcore.com,ops-team@adxcore.com'
        subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          🛡️ SECURITY ALERT 🛡️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Investigate immediately for potential security breach.
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: 'SECURITY ALERT'
        text: |
          {{ range .Alerts }}
          🛡️ *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']