groups:
- name: adx-core-services
  rules:
  # Service Health Alerts
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} has been down for more than 1 minute."

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High error rate on {{ $labels.job }}"
      description: "Error rate is {{ $value }} errors per second on {{ $labels.job }}."

  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High latency on {{ $labels.job }}"
      description: "95th percentile latency is {{ $value }}s on {{ $labels.job }}."

  # Resource Usage Alerts
  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.job }}"
      description: "CPU usage is {{ $value }}% on {{ $labels.job }}."

  - alert: HighMemoryUsage
    expr: process_resident_memory_bytes / 1024 / 1024 > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.job }}"
      description: "Memory usage is {{ $value }}MB on {{ $labels.job }}."

  # Database Alerts
  - alert: PostgreSQLDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL is down"
      description: "PostgreSQL database is down."

  - alert: PostgreSQLHighConnections
    expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connection usage"
      description: "PostgreSQL connection usage is {{ $value }}%."

  - alert: PostgreSQLSlowQueries
    expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL slow queries detected"
      description: "PostgreSQL query efficiency is low: {{ $value }}."

  # Redis Alerts
  - alert: RedisDown
    expr: redis_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis cache is down."

  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis high memory usage"
      description: "Redis memory usage is {{ $value }}%."

  # Temporal Alerts
  - alert: TemporalDown
    expr: temporal_service_requests_total == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Temporal server is down"
      description: "Temporal workflow server is not responding."

  - alert: HighWorkflowFailureRate
    expr: rate(temporal_workflow_completed_total{status="failed"}[5m]) / rate(temporal_workflow_completed_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High workflow failure rate"
      description: "Workflow failure rate is {{ $value }} on Temporal."

  # Disk Space Alerts
  - alert: DiskSpaceHigh
    expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Disk space usage high"
      description: "Disk usage is {{ $value }}% on {{ $labels.device }}."

  - alert: DiskSpaceCritical
    expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 95
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Disk space critically low"
      description: "Disk usage is {{ $value }}% on {{ $labels.device }}."

- name: adx-core-business
  rules:
  # Business Logic Alerts
  - alert: HighTenantCreationFailures
    expr: rate(tenant_creation_failures_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High tenant creation failure rate"
      description: "Tenant creation failure rate is {{ $value }} per second."

  - alert: FileUploadFailures
    expr: rate(file_upload_failures_total[5m]) > 0.2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High file upload failure rate"
      description: "File upload failure rate is {{ $value }} per second."

  - alert: AuthenticationFailures
    expr: rate(authentication_failures_total[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High authentication failure rate"
      description: "Authentication failure rate is {{ $value }} per second."

  - alert: QuotaExceeded
    expr: quota_usage_percentage > 90
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Quota usage high for tenant {{ $labels.tenant_id }}"
      description: "Quota usage is {{ $value }}% for tenant {{ $labels.tenant_id }}."

- name: adx-core-security
  rules:
  # Security Alerts
  - alert: SuspiciousActivity
    expr: rate(security_events_total{type="suspicious"}[5m]) > 0.1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Suspicious security activity detected"
      description: "Suspicious activity rate is {{ $value }} events per second."

  - alert: FailedLoginAttempts
    expr: rate(login_attempts_total{status="failed"}[5m]) > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High failed login attempts"
      description: "Failed login rate is {{ $value }} attempts per second."

  - alert: UnauthorizedAccess
    expr: rate(http_requests_total{status="403"}[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High unauthorized access attempts"
      description: "Unauthorized access rate is {{ $value }} per second."