groups:
  - name: adx-core-microservices
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.job }}"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency on {{ $labels.job }}"
          description: "95th percentile latency is {{ $value }}s on {{ $labels.job }}"

      # Resource usage alerts
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.name }}"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.name }}"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.name }}"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.name }}"

      # Database alerts
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is {{ $value | humanizePercentage }}"

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding"

      # Temporal workflow alerts
      - alert: TemporalWorkflowFailures
        expr: rate(temporal_workflow_failed_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Temporal workflow failure rate"
          description: "Temporal workflow failure rate is {{ $value }} failures per second"

      - alert: TemporalHighQueueDepth
        expr: temporal_task_queue_depth > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Temporal task queue depth"
          description: "Temporal task queue depth is {{ $value }} on {{ $labels.task_queue }}"

      # Tenant-specific alerts
      - alert: TenantQuotaExceeded
        expr: tenant_quota_usage_ratio > 0.95
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tenant quota exceeded"
          description: "Tenant {{ $labels.tenant_id }} has exceeded {{ $value | humanizePercentage }} of quota for {{ $labels.resource_type }}"

      # File service alerts
      - alert: FileStorageHighUsage
        expr: file_storage_usage_ratio > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "File storage usage high"
          description: "File storage usage is {{ $value | humanizePercentage }} for tenant {{ $labels.tenant_id }}"

      # Security alerts
      - alert: HighFailedAuthAttempts
        expr: rate(auth_failed_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High failed authentication attempts"
          description: "Failed authentication rate is {{ $value }} attempts per second"

      - alert: SuspiciousActivity
        expr: rate(security_suspicious_activity_total[5m]) > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Suspicious security activity detected"
          description: "Suspicious activity rate is {{ $value }} events per second"

  - name: adx-core-infrastructure
    rules:
      # Disk space alerts
      - alert: DiskSpaceHigh
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space low on {{ $labels.instance }}"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.instance }}"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space critically low on {{ $labels.instance }}"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.instance }}"

      # Load balancer alerts
      - alert: LoadBalancerDown
        expr: nginx_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Load balancer is down"
          description: "Nginx load balancer is not responding"

      - alert: HighRequestRate
        expr: rate(nginx_http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request rate"
          description: "Request rate is {{ $value }} requests per second"