# Prometheus Configuration for ADX Core Production
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ADX Core Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'workflow-service'
    static_configs:
      - targets: ['workflow-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'tenant-service'
    static_configs:
      - targets: ['tenant-service:8085']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:8088']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s